#!/bin/bash

# (ɔ) 2020 endorfina <dev.endorfina@outlook.com>
# WTFPL

readonly PROGNAME=${0##*/}

verbose()
{
    if [[ $OPT_VERBOSE == yes ]]
    then
        printf '[ %s ]\n' >&2 "$*"
    fi
}

cleanup()
{
    if [[ -n $TMP_FILE && -f $TMP_FILE ]]
    then
        verbose "Clearing temp file"
        rm "$TMP_FILE"
    fi
}

die()
{
    echo >&2 '💀' "$PROGNAME !!" "$@"
    cleanup
    exit 1
}

print_manual()
{
    cat << _END
Usage: \$ $PROGNAME command [-hv] [-l NUM]

Commands:

  new, add
        Opens up an empty buffer in your EDITOR.
        Then, provided it's not empty, $PROGNAME will
        save the buffer in a shared record file.

  show, print, sh, pr
        Prints all saved notes in a reverse
        chronological order to stdout.

  open, op
        Forwards the path to the record file
        as an argument to your EDITOR.

  delete, remove, del, rm
        $PROGNAME will erase your current record.

Options:

  -l NUM : shows up to NUM entries (applicable only
        when printing to stdout).

  -h    prints this help.

  -v    shows verbose logs.

_END
}

TMP_FILE=
NOTE_COMMAND=
OPT_VERBOSE=no
OPT_LIMIT=0

set -o pipefail

while [[ $# -gt 0 ]]
do
    ARG_ITER=${1#-}
    shift

    ARG_SIZE=${#ARG_ITER}

    while [[ -n $ARG_ITER ]]
    do
        case $ARG_ITER in
            v*)
                OPT_VERBOSE='yes'
                ;;

            l*)
                ARG_ITER=${ARG_ITER#?}

                if [[ -n $ARG_ITER ]]
                then
                    OPT_LIMIT=$ARG_ITER
                    ARG_ITER=
                else
                    OPT_LIMIT=$1
                    shift
                fi

                case $OPT_LIMIT in
                    *[![:digit:]]*|'') die "Wrong -l argument \"$OPT_LIMIT\"" ;;
                esac
                ;;

            h*)
                print_manual
                exit 0
                ;;

            *)
                if [[ -z $NOTE_COMMAND && $ARG_SIZE -eq ${#ARG_ITER} ]]
                then
                    readonly NOTE_COMMAND=$ARG_ITER
                    ARG_ITER=
                else
                    die "Invalid option \"$ARG_ITER\""
                fi
                ;;
        esac

        ARG_ITER=${ARG_ITER#?}
    done
done

read_record()
{
    # shellcheck disable=SC1003
    sed -e '/^'"$TAG"'/!s~^~'$'\t''~' -e 's~^'"$TAG"' \(.*\)$~-- [[ \1 ]]\'$'\n''~' "$RECORD"
}

check_for_tty()
{
    [[ -t 0 && -t 1 ]] || die "stdin and stdout must both be ttys"
}

: "${EDITOR?}" # die early if EDITOR isn't defined

readonly RECORD=${XDG_DATA_HOME:-"$HOME/.local/share"}/note_record
verbose "Record file at: $RECORD"
readonly TAG='%=--=%' # it's a bone!

case $NOTE_COMMAND in
    new|add)
        check_for_tty

        # shellcheck disable=SC2015
        TMP_FILE=$(mktemp) && [[ -w $TMP_FILE ]] || die "Failed to create a temporary file"
        readonly TMP_FILE

        "$EDITOR" 2>/dev/null "$TMP_FILE" || die "EDITOR failed"

        WORDS=$(wc -w < "$TMP_FILE") || die "Couldn't get word count"
        readonly WORDS="${WORDS#"${WORDS%%[![:space:]]*}"}"

        [[ $WORDS -lt 1 ]] && die "No words written, discarding note"
        verbose "Counted $WORDS words"

        REC_DIR=${RECORD%/*}
        [[ -d $REC_DIR ]] || mkdir -p "$REC_DIR" || die "Couldn't create directory \"$REC_DIR\""

        [[ ! -r $RECORD ]] || echo | cat - "$RECORD" >> "$TMP_FILE" || die "Couldn't merge the record file with the note"
        echo "$TAG $(date '+%d %b %H:%M')" | cat - "$TMP_FILE" > "$RECORD"
        cleanup
        ;;

    sh|pr|show|print)
        [[ -r $RECORD ]] || die "No record exists"

        if [[ $OPT_LIMIT -gt 0 ]]
        then
            verbose "Limit set to $OPT_LIMIT"

            i=0

            read_record | while read -r
            do
                case $REPLY in
                    --*)
                        (( ++i ))
                        [[ $i -gt $OPT_LIMIT ]] && break

                        printf '%3i. %s\n' "$i" "${REPLY#--}"
                        ;;

                    *)
                        printf '%s\n' "$REPLY"
                        ;;
                esac
            done
        else
            read_record
        fi
        ;;

    op|open)
        [[ -r $RECORD ]] || die "No record exists"
        check_for_tty

        "$EDITOR" 2>/dev/null "$RECORD"
        ;;

    del|rm|delete|remove)
        rm "$RECORD" || die "Nothing to delete"
        ;;

    *)
        print_manual

        die "Invalid command \"$NOTE_COMMAND\""
        ;;
esac

