#!/bin/bash

# (ɔ) 2020 endorfina <dev.endorfina@outlook.com>
# WTFPL

readonly PROGNAME=${BASH_SOURCE[0]##*/}

TMP_FILE=

verbose()
{
    if [[ $OPT_VERBOSE == yes ]]
    then
        echo >&2 '[' "$@" ']'
    fi
}

cleanup()
{
    if [[ -n $TMP_FILE && -f $TMP_FILE ]]
    then
        verbose "Clearing temp file"
        rm "$TMP_FILE"
    fi
}

die()
{
    echo >&2 '💀' "$PROGNAME !!" "$@"
    cleanup
    exit 1
}

print_manual()
{
    cat << _END
Usage: \$ $PROGNAME command [-hv]

Commands:

  new, add
        Opens up an empty buffer in your EDITOR.
        Then, provided it's not empty, $PROGNAME will
        save the buffer in a shared record file.

  show, print, sh, pr
        Prints all saved notes in a reverse
        chronological order to stdout.

  delete, remove, del, rm
        $PROGNAME will erase your current record.

Options:

  -l NUM : shows up to NUM entries (applicable only
        when printing to stdout).

  -h    prints this help.

  -v    shows verbose logs.

_END
}

[[ $# -lt 1 ]] && print_manual && die

readonly NOTE_COMMAND=$1
shift
OPT_VERBOSE=no
OPT_LIMIT=0

set -o pipefail

while [[ $# -gt 0 ]]
do
    ARG_ITER=${1#-}
    shift

    for (( i=0; i<${#ARG_ITER}; i++ ))
    do
        case ${ARG_ITER:$i:1} in
            v)
                OPT_VERBOSE='yes'
                ;;

            l)
                (( i++ ))
                if [[ $i -lt ${#ARG_ITER} ]]
                then
                    OPT_LIMIT=${ARG_ITER:$i}
                    i=${#ARG_ITER}
                else
                    OPT_LIMIT=$1
                    shift
                fi

                [[ $OPT_LIMIT =~ [^0-9] ]] && die "Wrong -l argument \"$OPT_LIMIT\""
                ;;

            h)
                print_manual
                exit 0
                ;;

            *)
                die "Invalid option \"$ARG_ITER\""
                ;;
        esac
    done
done

readonly EDIT=${EDITOR?}
readonly RECORD=${XDG_DATA_HOME:-"$HOME/.local/share"}/note_record
verbose "Record file at: $RECORD"
readonly TAG='%=--=%' # it's a bone!

case $NOTE_COMMAND in
    new|add)
        [[ -t 0 && -t 1 ]] || die "stdin and stdout must both be a tty"

        # shellcheck disable=SC2015
        TMP_FILE=$(mktemp) && [[ -w $TMP_FILE ]] || die "Failed to create a temporary file"
        readonly TMP_FILE

        "$EDIT" 2>/dev/null "$TMP_FILE" || die "Neovim failed"

        WORDS=$(wc -w < "$TMP_FILE")
        WORDS=${WORDS#[[:space:]]*}

        [[ $WORDS -lt 1 ]] && die "No words written, discarding note"
        verbose "Counted $WORDS words"

        REC_DIR=${RECORD%/*}
        [[ -d $REC_DIR ]] || mkdir -p "$REC_DIR" || die "Couldn't create directory \"$REC_DIR\""

        [[ ! -r $RECORD ]] || echo | cat - "$RECORD" >> "$TMP_FILE" || die "Couldn't merge the record file with the note"
        echo "$TAG $(date '+%d %b %H:%M')" | cat - "$TMP_FILE" > "$RECORD"
        cleanup
        ;;

    sh|pr|show|print)
        [[ -r $RECORD ]] || die "No record exists"

        # shellcheck disable=SC1003
        RUN=(sed -e '/^'"$TAG"'/!s~^~'$'\t''~' -e 's~^'"$TAG"' \(.*\)$~-- [[ \1 ]]\'$'\n''~' "$RECORD")
        readonly RUN

        if [[ $OPT_LIMIT -gt 0 ]]
        then
            verbose "Limit set to $OPT_LIMIT"

            i=0

            "${RUN[@]}" | while read -r
            do
                if [[ $REPLY == --* ]]
                then
                    (( i++ ))
                    [[ $i -gt $OPT_LIMIT ]] && break
                fi

                echo "$REPLY"
            done
        else
            "${RUN[@]}"
        fi
        ;;

    del|rm|delete|remove)
        rm "$RECORD" || die "Nothing to delete"
        ;;

    *)
        print_manual

        die "Invalid command \"$NOTE_COMMAND\""
        ;;
esac

